
apiVersion: v1
kind: Pod
metadata:
  name: logger-pod
spec:
  containers:
    - name: busybox
      image: busybox
      command: ["/bin/sh", "-c"]
      args:
        - while true; do echo "$(date) - log entry" >> /data/logs.txt; sleep 5; done
      volumeMounts:
        - name: app-logs
          mountPath: /data
  volumes:
    - name: app-logs
      persistentVolumeClaim:
        claimName: pvc-app-logs

