
---
- name: Configure Nginx Web Server
  hosts: all
  become: yes
  tasks:
    - name: Install Nginx
      ansible.builtin.apt:
        name: nginx
        state: present
        update_cache: yes

    - name: Start and enable Nginx service
      ansible.builtin.service:
        name: nginx
        state: started
        enabled: yes

    - name: Customize default web page
      ansible.builtin.copy:
        content: |
          <html>
          <head><title>Welcome to Ansible Web Server</title></head>
          <body style="font-family: Arial; text-align: center;">
          <h1>Hello from Ansible!</h1>
          <p>This web page was deployed automatically by Ansible 🚀</p>
          </body>
          </html>
        dest: /var/www/html/index.nginx-debian.html
        owner: www-data
        group: www-data
        mode: '0644'

