---
- name: Install Java 17 for Jenkins
  apt:
    name: openjdk-17-jdk
    state: present
    update_cache: yes

- name: Remove old Jenkins key if exists
  file:
    path: /usr/share/keyrings/jenkins-keyring.asc
    state: absent

- name: Add Jenkins GPG key
  get_url:
    url: https://pkg.jenkins.io/debian-stable/jenkins.io-2023.key
    dest: /usr/share/keyrings/jenkins-keyring.asc
    mode: '0644'

- name: Add Jenkins APT repository
  apt_repository:
    repo: "deb [signed-by=/usr/share/keyrings/jenkins-keyring.asc] https://pkg.jenkins.io/debian-stable binary/"
    filename: jenkins
    state: present

- name: Install Jenkins
  apt:
    name: jenkins
    state: present
    update_cache: yes

- name: Fix Jenkins directory permissions
  file:
    path: /var/lib/jenkins
    owner: jenkins
    group: jenkins
    recurse: yes
  ignore_errors: yes

- name: Remove stale Jenkins PID file
  file:
    path: /var/run/jenkins/jenkins.pid
    state: absent
  ignore_errors: yes

- name: Ensure Jenkins log directory exists
  file:
    path: /var/log/jenkins
    state: directory
    owner: jenkins
    group: jenkins
    mode: '0755'

- name: Reload systemd daemon
  systemd:
    daemon_reload: yes

- name: Start Jenkins service
  systemd:
    name: jenkins
    state: restarted
    enabled: yes

- name: Wait for Jenkins port 8080
  wait_for:
    port: 8080
    delay: 10
    timeout: 60

- name: Confirm Jenkins running
  uri:
    url: http://localhost:8080
    status_code: [200, 403]
  register: jenkins_check
  ignore_errors: no

- name: Debug Jenkins status
  debug:
    msg: >
      {% if jenkins_check.status in [200, 403] %}
        Jenkins is running successfully on port 8080
      {% else %}
        Jenkins failed to start, check logs with "journalctl -xeu jenkins"
      {% endif %}

